#!/usr/bin/env python

# input: layer{1-7} ( after generated by split.awk, they need to be dealt with the format before being used as the input of this script )
# output: file trs, in which thresholds are recorded

import numpy as np
import math
import linecache
#from fractions import Fraction

pct = 0.75

logfile = file("trs", 'w')

for i in range(1,8):
  print i

  tmp = 'layer{n}'
  tmp2 = tmp.format(n=i)
  layer = np.loadtxt(tmp2)
    
  print layer.shape
  layer = layer.flatten()
  print "layer.shape[0]:",layer.shape[0]

  # num of zero
  zero_id = np.where(layer==0)
  zero_subarray = layer[zero_id]
  zero_num = zero_subarray.shape[0]
  print "0:",zero_num

  # positive part
  positive_id = np.where(layer>0)[0]
  positive_subarray = layer[positive_id]
  print "positive_subarray.shape:",positive_subarray.shape[0]
  n_positive = ( positive_subarray.shape[0] + 0.5 * zero_num ) * (1-pct) # prune n value
  ind = np.argpartition(positive_subarray, -n_positive)[-n_positive:] # the max n values
  positive_tr = positive_subarray[ind][0]
  print >> logfile, tmp2
  print >> logfile, "positive threshold:", positive_tr

  # negative part
  negative_id = np.where(layer<0)[0]
  negative_subarray = layer[negative_id]
  n_negative = ( negative_subarray.shape[0] + 0.5 * zero_num ) * (pct) + 1 - 0.5 * zero_num # save n value
  ind = np.argpartition(negative_subarray, -n_negative)[-n_negative:] # the max n values
  negative_tr = negative_subarray[ind][0]
  print >> logfile, "negative threshold:", negative_tr

  print "n_positive:",n_positive
  print "n_negative:",n_negative

