#!/usr/bin/env python

# input: layer{1-7}.txt ( after generated by split.awk, they need to be dealt with the format before being used as the input of this script )
# output: file trs, in which thresholds are recorded

import numpy as np
import math
import linecache

pct = 0.2

logfile = file("trs", 'w')

for i in range(1,8):
  print i

  tmp = 'layer{n}.txt'
  tmp2 = tmp.format(n=i)
  layer = np.loadtxt(tmp2)
    
  print layer.shape
  layer = layer.flatten()
  print "layer.shape[0]:",layer.shape[0]

  # positive part
  n_max = layer.shape[0] * (1-pct) # prune n value
  ind = np.argpartition(layer, -n_max)[-n_max:] # the max n values
  tr = layer[ind][0]
  print >> logfile, tmp2
  print >> logfile, "threshold:", tr

